main: com.izanagicraft.librarian.bukkit.IzanagiLibrarianPlugin
name: 'izanagi-librarian'
version: ${version}
author:
  - sanguine6660
api-version: 1.20
description: ${description}
depend:
  - PlaceholderAPI
#  - ProtocolLib
  - Vault
website: https://github.com/IzanagiCraft/izanagi-librarian
load: STARTUP
